spring:
  output:
    ansi:
      enabled: always

  kafka:
    producer:
      bootstrap-servers: ${kafka_bootstrap_servers:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
